hibernate:
    connection:
        driver_class: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/store
        username: andrew
        password: password
    show_sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hbm2ddl:
        auto: update
    cache:
        provider_class: org.hibernate.cache.NoCacheProvider
    current_session_context_class: thread
